basic:
  load_weight: src/pretrained/model/model.pt
  uint8_transform: False
  cuda: True
  # add_haze: True

train:
  data_path: data/train/custom_dataset
  crops: 15
  crop_size: 20
  epochs: 10
  batch_size: 4
  learning_rate: 0.0001
  alpha: 0.99
  momentum: 0.7
  gamma: 0.1
  scheduler_steps: 5

validate:
  data_path: data/Middleburry

test:
  data_path: data/Middleburry
  clean_data_path: /

predict:
  data_path: data/DatasetForSomeMoreResults
  save_dir: src/output/predictions
  uint8_transform: False
  add_ext_haze: False

output:
  image_dir: data/output
  weight_dir: src/output/model_parameters/model

env:
  transmission_map:
    random_sampler: True
    low: 0.5
    high: 0.7
  atm_light: 1.0

image:
  size_reduction: False
  max_size: 600